In [1]:
import numpy as np
import pandas as pd
import pandas_ta as ta
import yfinance as yf
import datetime
import matplotlib as mpl
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

mpl.rcParams['axes.unicode_minus']=False
mpl.rcParams['font.sans-serif'] = ['SimHei']

In [3]:
# Set up the ticker and the date range
ticker_symbol = "META"
start_date = "2010-01-01"
end_date = datetime.datetime.now().strftime('%Y-%m-%d')

# Fetch the data
stock_data = yf.download(ticker_symbol,start=start_date, end=end_date)
stock_data.tail(6)

[*********************100%***********************]  1 of 1 completed

,Open,High,Low,Close,Adj Close,Volume
Date,,,,,,
2023-08-01,317.540009,324.140015,314.660004,322.709991,322.709991,22817900
2023-08-02,318.000000,318.390015,310.649994,314.309998,314.309998,20461100
2023-08-03,309.929993,315.950012,309.929993,313.190002,313.190002,15180200
2023-08-04,314.959991,318.410004,310.200012,310.730011,310.730011,17600200
2023-08-07,313.230011,317.070007,310.459991,316.559998,316.559998,16236500
2023-08-08,314.399994,317.890015,310.109985,312.640015,312.640015,15163700

In [4]:
stock_data["SMA_short"] = ta.sma(stock_data['Close'], length=21, append=True)
stock_data["SMA_long"] = ta.sma(stock_data['Close'], length=252, append=True)

In [5]:
stock_data.tail(9)

,Open,High,Low,Close,Adj Close,Volume,SMA_short,SMA_long
Date,,,,,,,,
2023-07-27,325.119995,325.350006,309.839996,311.709991,311.709991,64229200,298.692380,183.292817
2023-07-28,316.880005,326.200012,314.250000,325.480011,325.480011,39220300,300.606190,183.911468
2023-07-31,323.690002,325.660004,317.589996,318.600006,318.600006,25799600,302.371428,184.537976
2023-08-01,317.540009,324.140015,314.660004,322.709991,322.709991,22817900,304.072856,185.187222
2023-08-02,318.000000,318.390015,310.649994,314.309998,314.309998,20461100,305.419999,185.799841
2023-08-03,309.929993,315.950012,309.929993,313.190002,313.190002,15180200,306.316190,186.406984
2023-08-04,314.959991,318.410004,310.200012,310.730011,310.730011,17600200,307.208572,186.970198
2023-08-07,313.230011,317.070007,310.459991,316.559998,316.559998,16236500,308.448095,187.549524
2023-08-08,314.399994,317.890015,310.109985,312.640015,312.640015,15163700,309.330953,188.127024